### ISSUE TITLE
can you provide with the code to collect tweets

### ISSUE THREAD

**Issue by 011k** [sejaldua/covid19-vaccy-tweets-NLP#1]

**Comment by sejaldua** [comment]
The dataset is maintained by Kaggle user [Gabriel Preda](https://www.kaggle.com/gpreda) and is updated daily.

> The data is collected using tweepy Python package to access Twitter API. For each of the vaccine I use relevant search term (most frequently used in Twitter to refer to the respective vaccine)

If you would like to collect tweets yourself, with specific search terms for each respective vaccine you are interested in, I suggest reaching out to Gabriel to see if he will provide you with some starter code.
